name: Silkworm Sound
favicon: null
layout_spectrum: 0.73665
typography_spectrum: 0.07444
title: 'Silkworm Sound: recording studio in Durham, NC'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cac1ba'
    - '#697b47'
    - '#df5236'
    - '#3a4b1e'
    - '#452006'
  brandStrength: 1
  lightness: 1
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
